version: "3.7"

services:
  helios:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_MQTT_URL=ws://127.0.0.1:9001
    ports:
      - 8081:80
    volumes:
      - ./config.json:/opt/app/config.json
    env_file:
      - .env
    environment:
      OPENWEATHER_API_KEY: $OPENWEATHER_API_KEY
    depends_on:
      - mqtt
    links:
      - "mqtt:mqtt"

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
